version: '3'

services:
  ark-identify-service:
    image: 469995363/ark-identify-starter:1.0-SNAPSHOT
    ports:
      - 10010:80
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ark_internal_access
      - ark_external_access # db access

  ark-simple-resource-service:
    image: 469995363/ark-simple-resource-server:1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8090:80
    networks:
      - ark_internal_access
      - ark_external_access # db access
  ark-gateway-service:
    image: 469995363/ark-gateway:1.0-SNAPSHOT
    ports:
      - 10000:80
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ARK_IDENTIFY_SERVICE=ark-identify-service
      - ARK_SIMPLE_RESOURCE_SERVICE=ark-simple-resource-service
    depends_on:
      - ark-identify-service
      - ark-simple-resource-service
    networks:
      - ark_internal_access
      - ark_external_access # db access

networks:
  ark_internal_access:
    driver: bridge
    internal: true
  ark_external_access:
    driver: bridge

