version: '3'

services:
  ark-nginx-gateway:
    image: nginx:1.19.0
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx.template:/etc/nginx/templates/default.conf.template:ro
    networks:
      - ark_internal_access

networks:
  ark_internal_access:
    driver: bridge
    internal: true


