server:
  port: 10000

logging:
  level:
    root: debug

spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:10000/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://account.ark.com/oauth2/authorize
            token-uri: http://account.ark.com/oauth2/token
            jwk-set-uri: http://account.ark.com/oauth2/jwks