spring:
  thymeleaf:
    cache: false
  application:
    name: ark-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://${ARK_SIMPLE_RESOURCE_SERVICE:ark-simple-resource}
          predicates:
            - Path=/auth-info,/message,/auth-message
#          filters:
#            - name: AddJwtToken
        - id: ark-identify
          uri: http://${ARK_IDENTIFY_SERVICE:ark-account}
          predicates:
            - Path=/ark-identify/**