server:
  port: 8090

spring:
  application:
    name: ark-simple-resource-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

ark:
  jwt:
    public.key: classpath:app.pub
    private.key: classpath:app.key